org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.153.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0-alpha.1

mod_version=1.0.0+26.2
maven_group=eu.donyka
archives_base_name=hitcolor
minecraft_dependency=>=26.2 <26.3
java_version=25
