org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.1.2
loader_version=0.19.2
fabric_api_version=0.148.0+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8

mod_version=1.0.0+26.1.x
maven_group=eu.donyka
archives_base_name=hitcolor
minecraft_dependency=>=26.1 <26.2
java_version=25
